[package]
name = "rust-webui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webui-sys = { path = "webui-sys" }

[workspace]
members = ["webui-sys"]
