# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = ["webui-sys", "rust-webui"]
resolver = "2"


[workspace.dependencies]
webui-sys = { path = "webui-sys" }
rust-webui = { path = "rust-webui" }
